##SWITCHES
set_property PACKAGE_PIN B16 [get_ports {ina[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[0]}]
set_property PACKAGE_PIN E14 [get_ports {ina[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[1]}]
set_property PACKAGE_PIN E13 [get_ports {ina[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[2]}]
set_property PACKAGE_PIN C13 [get_ports {ina[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[3]}]
set_property PACKAGE_PIN B13 [get_ports {inb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[0]}]
set_property PACKAGE_PIN A13 [get_ports {inb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[1]}]
set_property PACKAGE_PIN D14 [get_ports {inb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[2]}]
set_property PACKAGE_PIN A14 [get_ports {inb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[3]}]
set_property PACKAGE_PIN B15 [get_ports {opcode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {opcode[0]}]
set_property PACKAGE_PIN A15 [get_ports {opcode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {opcode[1]}]
set_property PACKAGE_PIN E16 [get_ports {opcode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {opcode[2]}]

##LED
set_property PACKAGE_PIN AA21 [get_ports {ALUout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[0]}]
set_property PACKAGE_PIN P19 [get_ports {ALUout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[1]}]
set_property PACKAGE_PIN P20 [get_ports {ALUout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[2]}]
set_property PACKAGE_PIN R19 [get_ports {ALUout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[3]}]
set_property PACKAGE_PIN U22 [get_ports Led7]
set_property IOSTANDARD LVCMOS33 [get_ports Led7]