##SWITCHES
set_property PACKAGE_PIN B16 [get_ports {ina[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[0]}]
set_property PACKAGE_PIN E14 [get_ports {ina[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[1]}]
set_property PACKAGE_PIN E13 [get_ports {ina[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[2]}]
set_property PACKAGE_PIN C13 [get_ports {ina[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[3]}]
set_property PACKAGE_PIN B13 [get_ports {inb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[0]}]
set_property PACKAGE_PIN A13 [get_ports {inb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[1]}]
set_property PACKAGE_PIN D14 [get_ports {inb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[2]}]
set_property PACKAGE_PIN A14 [get_ports {inb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[3]}]
set_property PACKAGE_PIN D15 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports cin]

##LED
set_property PACKAGE_PIN AA21 [get_ports {sum[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[0]}]
set_property PACKAGE_PIN P19 [get_ports {sum[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[1]}]
set_property PACKAGE_PIN P20 [get_ports {sum[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[2]}]
set_property PACKAGE_PIN R19 [get_ports {sum[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[3]}]
set_property PACKAGE_PIN T20 [get_ports cout]
set_property IOSTANDARD LVCMOS33 [get_ports cout]
set_property PACKAGE_PIN U22 [get_ports Led7]
set_property IOSTANDARD LVCMOS33 [get_ports Led7]