
##clk
set_property PACKAGE_PIN K18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
##RSTn
set_property PACKAGE_PIN B16 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]

##keyboard
set_property PACKAGE_PIN AA10 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property PACKAGE_PIN V10 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property PACKAGE_PIN W10 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property PACKAGE_PIN AA9 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property PACKAGE_PIN AB10 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property PACKAGE_PIN W11 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property PACKAGE_PIN AA11 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property PACKAGE_PIN T14 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]

##lcd
set_property PACKAGE_PIN J21 [get_ports LCD_CS]
set_property PACKAGE_PIN L13 [get_ports LCD_RST]
set_property PACKAGE_PIN J20 [get_ports LCD_RS]
set_property PACKAGE_PIN M16 [get_ports LCD_WR]
set_property PACKAGE_PIN M15 [get_ports LCD_RD]
set_property PACKAGE_PIN K19 [get_ports LCD_BLK]


set_property PACKAGE_PIN M13 [get_ports LCD_DATA[0]]
set_property PACKAGE_PIN L15 [get_ports LCD_DATA[1]]
set_property PACKAGE_PIN L14 [get_ports LCD_DATA[2]]
set_property PACKAGE_PIN K14 [get_ports LCD_DATA[3]]
set_property PACKAGE_PIN K13 [get_ports LCD_DATA[4]]
set_property PACKAGE_PIN K16 [get_ports LCD_DATA[5]]
set_property PACKAGE_PIN L16 [get_ports LCD_DATA[6]]
set_property PACKAGE_PIN L18 [get_ports LCD_DATA[7]]
set_property PACKAGE_PIN M18 [get_ports LCD_DATA[8]]
set_property PACKAGE_PIN J17 [get_ports LCD_DATA[9]]
set_property PACKAGE_PIN K17 [get_ports LCD_DATA[10]]
set_property PACKAGE_PIN H18 [get_ports LCD_DATA[11]]
set_property PACKAGE_PIN H17 [get_ports LCD_DATA[12]]
set_property PACKAGE_PIN H19 [get_ports LCD_DATA[13]]
set_property PACKAGE_PIN J19 [get_ports LCD_DATA[14]]
set_property PACKAGE_PIN M17 [get_ports LCD_DATA[15]]

set_property IOSTANDARD LVCMOS33 [get_ports LCD_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RST]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_WR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RD]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[8]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[9]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[10]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[11]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[12]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[13]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[14]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DATA[15]]
