##CLK
set_property PACKAGE_PIN K18 [get_ports clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50M]

##SWITCHES
set_property PACKAGE_PIN B16 [get_ports {ina[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[0]}]
set_property PACKAGE_PIN E14 [get_ports {ina[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[1]}]
set_property PACKAGE_PIN E13 [get_ports {ina[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[2]}]
set_property PACKAGE_PIN C13 [get_ports {ina[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[3]}]
set_property PACKAGE_PIN B13 [get_ports {inb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[0]}]
set_property PACKAGE_PIN A13 [get_ports {inb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[1]}]
set_property PACKAGE_PIN D14 [get_ports {inb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[2]}]
set_property PACKAGE_PIN A14 [get_ports {inb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[3]}]
set_property PACKAGE_PIN D15 [get_ports {inc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inc[0]}]
set_property PACKAGE_PIN B15 [get_ports {inc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inc[1]}]
set_property PACKAGE_PIN A15 [get_ports {inc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inc[2]}]
set_property PACKAGE_PIN E16 [get_ports {inc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inc[3]}]

##DIGITRON
set_property PACKAGE_PIN AA16 [get_ports {seg_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN AB15 [get_ports {seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
set_property PACKAGE_PIN AB16 [get_ports {seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
set_property PACKAGE_PIN AB17 [get_ports {seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
set_property PACKAGE_PIN W14 [get_ports {seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
set_property PACKAGE_PIN Y17 [get_ports {seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
set_property PACKAGE_PIN AA15 [get_ports {seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]
set_property PACKAGE_PIN Y16 [get_ports {seg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[7]}]
set_property PACKAGE_PIN Y14 [get_ports {seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN AB13 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN AA13 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN Y13 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN AB11 [get_ports {seg_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN AA14 [get_ports {seg_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[5]}]

