## clk
set_property PACKAGE_PIN K18      [get_ports clk]
set_property IOSTANDARD  LVCMOS33 [get_ports clk]
## rst_n
set_property PACKAGE_PIN B16      [get_ports rst_n]
set_property IOSTANDARD  LVCMOS33 [get_ports rst_n]

## keyborad
set_property PACKAGE_PIN AB10     [get_ports col[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports col[0]]
set_property PACKAGE_PIN W11      [get_ports col[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports col[1]]
set_property PACKAGE_PIN AA11     [get_ports col[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports col[2]]
set_property PACKAGE_PIN T14      [get_ports col[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports col[3]]

set_property PACKAGE_PIN AA9      [get_ports row]
set_property IOSTANDARD  LVCMOS33 [get_ports row]

## input data 
set_property PACKAGE_PIN E14      [get_ports a[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports a[0]]
set_property PACKAGE_PIN E13      [get_ports a[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports a[1]]
set_property PACKAGE_PIN C13      [get_ports a[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports a[2]]
set_property PACKAGE_PIN B13      [get_ports a[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports a[3]]
set_property PACKAGE_PIN A13      [get_ports a[4]]
set_property IOSTANDARD  LVCMOS33 [get_ports a[4]]

set_property PACKAGE_PIN D14      [get_ports b[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports b[0]]
set_property PACKAGE_PIN A14      [get_ports b[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports b[1]]
set_property PACKAGE_PIN D15      [get_ports b[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports b[2]]
set_property PACKAGE_PIN B15      [get_ports b[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports b[3]]
set_property PACKAGE_PIN A15      [get_ports b[4]]
set_property IOSTANDARD  LVCMOS33 [get_ports b[4]]

## result ready
set_property PACKAGE_PIN AA21     [get_ports res_rdy]
set_property IOSTANDARD  LVCMOS33 [get_ports res_rdy]

## 7-seg display
set_property PACKAGE_PIN Y14      [get_ports seg_sel[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[0]]
set_property PACKAGE_PIN AB13     [get_ports seg_sel[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[1]]
set_property PACKAGE_PIN AA13     [get_ports seg_sel[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[2]]
set_property PACKAGE_PIN Y13      [get_ports seg_sel[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[3]]
set_property PACKAGE_PIN AB11     [get_ports seg_sel[4]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[4]]
set_property PACKAGE_PIN AA14     [get_ports seg_sel[5]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_sel[5]]

set_property PACKAGE_PIN AA16     [get_ports seg_led[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[0]]
set_property PACKAGE_PIN AB15     [get_ports seg_led[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[1]]
set_property PACKAGE_PIN AB16     [get_ports seg_led[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[2]]
set_property PACKAGE_PIN AB17     [get_ports seg_led[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[3]]
set_property PACKAGE_PIN W14      [get_ports seg_led[4]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[4]]
set_property PACKAGE_PIN Y17      [get_ports seg_led[5]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[5]]
set_property PACKAGE_PIN AA15     [get_ports seg_led[6]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[6]]
set_property PACKAGE_PIN Y16      [get_ports seg_led[7]]
set_property IOSTANDARD  LVCMOS33 [get_ports seg_led[7]]

## LED
set_property PACKAGE_PIN U22      [get_ports led7]
set_property IOSTANDARD  LVCMOS33 [get_ports led7]